name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: [stable, beta]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
            
    - name: Build
      run: compile-features.sh
      
    - name: Run tests
      run: test.sh
    
